---
name: Build Calendar

permissions:
  contents: write

"on":
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    uses: paulte/calmerge/.github/workflows/build-calendar.yml@e3db678a059d2e5a0d56c38cd50d3c2bc7ed75b3 # main
