---
name: Check Configuration

permissions:
  contents: read

"on":
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  check:
    uses: paulte/calmerge/.github/workflows/check-configuration.yml@e3db678a059d2e5a0d56c38cd50d3c2bc7ed75b3 # main
